name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["Host-VS2022-Broken", "Host-VS2022-Fixed"]
        configuration: ["Debug", "RelWithDebInfo"]

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

    - name: configure and build
      run: |
        cmake --preset=${{ matrix.target }}
        cmake --build --preset=${{ matrix.target }}-${{ matrix.configuration }}

    - name: run executable
      run: |
        build/${{ matrix.target }}/source/based-on-emil/${{ matrix.configuration }}/based-on-emil.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce #v3.1.2
      with:
        name: ${{ matrix.target }}-${{ matrix.configuration }}-Full-Environment
        path: .
